# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_curric_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='title',
            new_name='name',
        ),
    ]
