# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mentor'),
        ('meetings', '0003_auto_20180818_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_data', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_task', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='curric',
            name='team',
        ),
        migrations.AddField(
            model_name='meeting',
            name='info',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='video',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Curric',
        ),
        migrations.AddField(
            model_name='studentmeeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
        migrations.AddField(
            model_name='studentmeeting',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
        migrations.AddField(
            model_name='mentormeeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
        migrations.AddField(
            model_name='mentormeeting',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Mentor'),
        ),
    ]
