# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20180820_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='info',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentormeeting',
            name='team_data',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='studentmeeting',
            name='web_task',
            field=models.CharField(max_length=1000),
        ),
    ]
