# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0008_auto_20180828_1436'),
        ('meetings', '0005_auto_20180822_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamMap.Team')),
            ],
        ),
    ]
