# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meetingteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormeeting',
            name='team_data',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='studentmeeting',
            name='web_task',
            field=models.CharField(max_length=100000),
        ),
    ]
