# Generated by Django 2.0.7 on 2019-07-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_remove_meeting_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormeeting',
            name='action_blueprint',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='mentormeeting',
            name='become_educated',
            field=models.FileField(default=0, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='mentormeeting',
            name='problem',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='mentormeeting',
            name='solution',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='mentormeeting',
            name='solution_results',
            field=models.CharField(default=0, max_length=600),
        ),
    ]
