# Generated by Django 2.0.7 on 2019-08-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_auto_20190802_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
