# Generated by Django 2.0.7 on 2019-08-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_meeting_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='mentormeeting',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentormeeting',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
