# Generated by Django 2.0.7 on 2019-08-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_auto_20190803_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentormeeting',
            name='action_blueprint',
        ),
        migrations.RemoveField(
            model_name='mentormeeting',
            name='become_educated',
        ),
        migrations.RemoveField(
            model_name='mentormeeting',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='mentormeeting',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='mentormeeting',
            name='solution_results',
        ),
        migrations.RemoveField(
            model_name='mentormeeting',
            name='team_data',
        ),
    ]
