# Generated by Django 2.0.7 on 2019-08-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0017_auto_20190803_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormeeting',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentormeeting',
            name='not_started',
            field=models.BooleanField(default=True),
        ),
    ]
