# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoProj', models.CharField(max_length=1000)),
                ('problemState', models.CharField(max_length=200)),
                ('is_relevant', models.BooleanField(default=False)),
                ('DoesNotExist', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('bigIssue', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('team_logo', models.FileField(upload_to=b'')),
                ('numMembers', models.IntegerField()),
                ('mentorName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='benchmark',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamMap.Team'),
        ),
    ]
