# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('create_team', 'Create a Team'), ('join_team', 'Join Team'))},
        ),
    ]
