# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mentor'),
        ('TeamMap', '0003_teamuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='mentorName',
        ),
        migrations.AddField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Mentor'),
            preserve_default=False,
        ),
    ]
