# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0005_team_accepting_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='numMembers',
            field=models.IntegerField(default=0),
        ),
    ]
