# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0008_auto_20180828_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Mentor'),
        ),
        migrations.AlterField(
            model_name='teamstudent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
