# Generated by Django 2.0.7 on 2018-11-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0009_auto_20180904_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
