# Generated by Django 2.0.7 on 2019-07-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0010_auto_20181102_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmark',
            name='problemState',
        ),
        migrations.AddField(
            model_name='benchmark',
            name='action_blueprint',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='become_educated',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='problem',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='solution',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='solution_results',
            field=models.CharField(default=0, max_length=600),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='infoProj',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
