# Generated by Django 2.0.7 on 2019-07-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0011_auto_20190720_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmark',
            name='become_educated',
            field=models.FileField(upload_to='media/'),
        ),
    ]
