# Generated by Django 2.0.7 on 2019-07-28 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0012_auto_20190720_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmark',
            name='action_blueprint',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='become_educated',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='solution_results',
        ),
        migrations.AddField(
            model_name='team',
            name='action_blueprint',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='team',
            name='become_educated',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='problem',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='solution',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='team',
            name='solution_results',
            field=models.CharField(default=0, max_length=600),
        ),
    ]
