# Generated by Django 2.0.7 on 2019-07-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0013_auto_20190728_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='become_educated',
            field=models.FileField(upload_to=''),
        ),
    ]
