# Generated by Django 2.0.7 on 2019-08-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0016_auto_20190729_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='action_blueprint',
        ),
        migrations.RemoveField(
            model_name='team',
            name='action_blueprint_done',
        ),
        migrations.RemoveField(
            model_name='team',
            name='action_blueprint_progress',
        ),
        migrations.RemoveField(
            model_name='team',
            name='become_educated',
        ),
        migrations.RemoveField(
            model_name='team',
            name='become_educated_done',
        ),
        migrations.RemoveField(
            model_name='team',
            name='become_educated_progress',
        ),
        migrations.RemoveField(
            model_name='team',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='team',
            name='problem_done',
        ),
        migrations.RemoveField(
            model_name='team',
            name='problem_progress',
        ),
        migrations.RemoveField(
            model_name='team',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='team',
            name='solution_done',
        ),
        migrations.RemoveField(
            model_name='team',
            name='solution_progress',
        ),
        migrations.RemoveField(
            model_name='team',
            name='solution_results',
        ),
        migrations.RemoveField(
            model_name='team',
            name='solution_results_done',
        ),
        migrations.RemoveField(
            model_name='team',
            name='solution_results_progress',
        ),
    ]
