# Generated by Django 2.0.7 on 2019-08-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0017_auto_20190803_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='action_blueprint',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='team',
            name='become_educated',
            field=models.FileField(default=0, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='team',
            name='problem',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='solution',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='team',
            name='solution_results',
            field=models.CharField(default=0, max_length=600),
        ),
    ]
