# Generated by Django 2.0.7 on 2020-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0018_auto_20190803_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='action_blueprint',
            field=models.CharField(blank=True, default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='become_educated',
            field=models.FileField(blank=True, default=0, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='problem',
            field=models.CharField(blank=True, default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='solution',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
        migrations.AlterField(
            model_name='team',
            name='solution_results',
            field=models.CharField(blank=True, default=0, max_length=600),
        ),
    ]
