# Generated by Django 2.0.7 on 2020-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMap', '0019_auto_20200514_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='action_blueprint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='become_educated',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='problem',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='solution',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='team',
            name='solution_results',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
